# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kerbores 的个人博客
email:  kerbores@zhcs.club
description: > # this means to ignore newlines until "baseurl:"
  Kerbores 的个人博客.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.zhcs.club" # the base hostname & protocol for your site
twitter_username: kerbores
github_username:  kerbores

# Build settings
markdown: kramdown
